Fix update generation with additionalIdentifiers (#732)
* Disable unhelpful pylint warning

pylint insists that `with` should be used on all disposable resources
but in this case the constructor call is in a helper method and the
consuming method does already use `with`. Given that this is a private
method it should be fine to ignore the warning in all cases.

* Fix update generation with additionalIdentifiers

If the `additionalIdentifiers` property is present in a resource schema
the `generate_update_example` method in `resource_client` will not work,
because it checks for unique keys from the create_model and passes
`self._additional_identifiers_paths` to a method that expects a list of
tuples of string, whereas it receives a list of sets of tuples of
string and will fail with

```
AttributeError: 'tuple' object has no attribute 'split'
```

Instead, check if the key is in any of the additional identifiers.

Related issue
-------------

https://github.com/aws-cloudformation/cloudformation-cli/issues/731